runtime: nodejs20
service: default
instance_class: F1

handlers:
  # Serve static files with proper caching
  - url: /static
    static_dir: build/static
    secure: always
    http_headers:
      Cache-Control: "public, max-age=31536000, immutable"

  # Define API routes to ensure they are handled by Node.js
  - url: /leaderboard
    script: auto
    secure: always

  - url: /update-cache
    script: auto
    secure: always

  - url: /ping
    script: auto
    secure: always

  # Serve the main index.html for React frontend (catch-all)
  - url: /.*
    static_files: build/index.html
    upload: build/index.html
    secure: always
    http_headers:
      Cache-Control: "no-cache, no-store, must-revalidate"
      Expires: "0"
      Pragma: "no-cache"
